# Generated by Django 6.0.4 on 2026-04-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_match_to_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_psychologist', to=settings.AUTH_USER_MODEL),
        ),
    ]
