# Generated by Django 6.0.4 on 2026-05-07 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_calendar_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recurring_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecurringAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('psychologist', 'day_of_week', 'start_time')},
            },
        ),
    ]
