# Generated by Django 6.0.4 on 2026-05-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recurring_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='slot_duration',
            field=models.PositiveIntegerField(default=60, help_text='Duración de cada sesión en minutos'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='slot_gap',
            field=models.PositiveIntegerField(default=0, help_text='Pausa entre sesiones en minutos'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_dates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cancellation', models.BooleanField(default=False)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.appointment')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_modifications', to=settings.AUTH_USER_MODEL)),
                ('recurring_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.recurringbooking')),
            ],
        ),
    ]
